title: Talaria Software
email: damien@talariasoftware.com
description: >- # this means to ignore newlines until "baseurl:"
  Software is a means to an end. Your real goals are to delight your customers, grow your business, and make people's lives better. Building software is only valuable when it helps you do those things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: talariasoftware
github_username:  talariasoftware

# Build settings
markdown: kramdown
timezone: America/Los_Angeles
plugins:
  - jekyll-feed
permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
